# Manejo de excepciones b√°sico

try:
    14/0
except:
    print("No podemos dividir entre cero")

# try:
#     print(x)
# except Exception as exception (NameError):
#     print(exception)

print("Final")